# -*- mode: ruby -*-
# vi: set ft=ruby :
master_ip = "172.19.0.100"
workers_net = "172.19.0.10" # 172.17.0.10x
agents_net = "172.19.0.20"  # 172.17.0.20x
n_workers = 1
n_agents = 2
box = "centos/7"

Vagrant.configure("2") do |config|
    # Manager master
    config.vm.define "master" do |node|
        node.vm.box = "#{box}"
        node.vm.provision :shell, path: "configure_manager.sh", args: "#{master_ip} master master"
        node.vm.network :private_network, ip: "#{master_ip}"
        node.vm.provider "libvirt" do |pmv|
          pmv.memory = 512
          pmv.cpus   = 1
      end
      node.vm.hostname = "master"
    end
    # Manager worker
    (1..n_workers).each do |i|
        config.vm.define "worker-#{i}" do |node|
            node.vm.box = "#{box}"
            node.vm.provision :shell, path: "configure_manager.sh", args: "#{master_ip} worker worker-#{i}"
            node.vm.network :private_network, ip: "#{workers_net}#{i}"
            node.vm.provider "libvirt" do |pmv|
              pmv.memory = 512
              pmv.cpus   = 1
          end
          node.vm.hostname = "worker-#{i}"
        end
    end
end
